/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef AUDIOMOSIFY_H
#define AUDIOMOSIFY_H

/* function declarations */
void init_audioMOSify(void);
Netsnmp_Node_Handler handle_audioMOSC;
Netsnmp_Node_Handler handle_audioMOSLO;

#endif /* AUDIOMOSIFY_H */
