/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "audioMOSify.h"

extern char mosc[12];
extern char moslo[12];


/** Initializes the audioMOSify module */
void
init_audioMOSify(void)
{
    const oid audioMOSC_oid[] = { 1,3,6,1,3,79,1,2,1 };
    const oid audioMOSLO_oid[] = { 1,3,6,1,3,79,1,2,2 };

  DEBUGMSGTL(("audioMOSify", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("audioMOSC", handle_audioMOSC,
                               audioMOSC_oid, OID_LENGTH(audioMOSC_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("audioMOSLO", handle_audioMOSLO,
                               audioMOSLO_oid, OID_LENGTH(audioMOSLO_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_audioMOSC(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     mosc,
                                     strlen(mosc));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_audioMOSC\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_audioMOSLO(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     moslo,
                                     strlen(moslo));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_audioMOSLO\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
