/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.notify.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "audioMOSify_traps.h"

extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;

int
send_audioMOSHit_trap( int ValueForAlerting )
{
    time_t now=time(0);
    char buffer[] = "Be carrefule ! The Quality is not good"; 
    

    netsnmp_variable_list  *var_list = NULL;
    const oid audioMOSHit_oid[] = { 1,3,6,1,3,79,1,0,1 };
    const oid audioTrapData_oid[] = { 1,3,6,1,3,79,1,0,0,2, 0 };
    const oid audioTrapTime_oid[] = { 1,3,6,1,3,79,1,0,0,1, 0 };
    
    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        audioMOSHit_oid, sizeof(audioMOSHit_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        audioTrapData_oid, OID_LENGTH(audioTrapData_oid),
        ASN_OCTET_STR,
        /* Set an appropriate value for audioTrapData */
        buffer, strlen(buffer));
    snmp_varlist_add_variable(&var_list,
        audioTrapTime_oid, OID_LENGTH(audioTrapTime_oid),
        ASN_INTEGER,
        /* Set an appropriate value for audioTrapTime */
        &now, sizeof(now));
    snmp_varlist_add_variable(&var_list,
        audioMOSHit_oid, OID_LENGTH(audioMOSHit_oid),
        ASN_INTEGER,
        &ValueForAlerting, sizeof(ValueForAlerting));

    /*
     * Add any extra (optional) objects here
     */

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
