/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.notify.conf
 */
#ifndef AUDIOMOSIFY_TRAPS_H
#define AUDIOMOSIFY_TRAPS_H

/* function declarations */
int send_audioMOSHit_trap(int);

#endif /* AUDIOMOSIFY_TRAPS_H */
