/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "audioConfigTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement audioConfigTable get routines.
 * TODO:240:M: Implement audioConfigTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table audioConfigTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * MOSIFY-AUDIO-MIB::audioConfigTable is subid 1 of audioConfigInfo.
 * Its status is Current.
 * OID: .1.3.6.1.3.79.1.1.1, length: 9
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement audioConfigTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param audioParamConfigName_ptr
 * @param audioParamConfigName_ptr_len
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
audioConfigTable_indexes_set_tbl_idx(audioConfigTable_mib_index *tbl_idx, char *audioParamConfigName_val_ptr,  size_t audioParamConfigName_val_ptr_len)
{
    DEBUGMSGTL(("verbose:audioConfigTable:audioConfigTable_indexes_set_tbl_idx","called\n"));

    /* audioParamConfigName(1)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
    tbl_idx->audioParamConfigName_len = sizeof(tbl_idx->audioParamConfigName)/sizeof(tbl_idx->audioParamConfigName[0]); /* max length */
    /*
     * make sure there is enough space for audioParamConfigName data
     */
    if ((NULL == tbl_idx->audioParamConfigName) ||
        (tbl_idx->audioParamConfigName_len <
         (audioParamConfigName_val_ptr_len))) {
        snmp_log(LOG_ERR,"not enough space for value (audioParamConfigName_val_ptr)\n");
        return MFD_ERROR;
    }
    tbl_idx->audioParamConfigName_len = audioParamConfigName_val_ptr_len;
    memcpy( tbl_idx->audioParamConfigName, audioParamConfigName_val_ptr, audioParamConfigName_val_ptr_len* sizeof(audioParamConfigName_val_ptr[0]) );
    

    return MFD_SUCCESS;
} /* audioConfigTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
audioConfigTable_indexes_set(audioConfigTable_rowreq_ctx *rowreq_ctx, char *audioParamConfigName_val_ptr,  size_t audioParamConfigName_val_ptr_len)
{
    DEBUGMSGTL(("verbose:audioConfigTable:audioConfigTable_indexes_set","called\n"));

    if(MFD_SUCCESS != audioConfigTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , audioParamConfigName_val_ptr, audioParamConfigName_val_ptr_len
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != audioConfigTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* audioConfigTable_indexes_set */


/*---------------------------------------------------------------------
 * MOSIFY-AUDIO-MIB::audioConfigTableEntry.audioParamConfigValue
 * audioParamConfigValue is subid 2 of audioConfigTableEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.3.79.1.1.1.1.2
 * Description:
A value related to an audio configuration parameter
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is DisplayString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * Extract the current value of the audioParamConfigValue data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param audioParamConfigValue_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param audioParamConfigValue_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by audioParamConfigValue.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*audioParamConfigValue_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update audioParamConfigValue_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
audioParamConfigValue_get( audioConfigTable_rowreq_ctx *rowreq_ctx, char **audioParamConfigValue_val_ptr_ptr, size_t *audioParamConfigValue_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != audioParamConfigValue_val_ptr_ptr) && (NULL != *audioParamConfigValue_val_ptr_ptr));
   netsnmp_assert( NULL != audioParamConfigValue_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:audioConfigTable:audioParamConfigValue_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the audioParamConfigValue data.
 * copy (* audioParamConfigValue_val_ptr_ptr ) data and (* audioParamConfigValue_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for audioParamConfigValue data
     */
    if ((NULL == (* audioParamConfigValue_val_ptr_ptr )) ||
        ((* audioParamConfigValue_val_ptr_len_ptr ) <
         (rowreq_ctx->data.audioParamConfigValue_len* sizeof(rowreq_ctx->data.audioParamConfigValue[0])))) {
        /*
         * allocate space for audioParamConfigValue data
         */
        (* audioParamConfigValue_val_ptr_ptr ) = malloc(rowreq_ctx->data.audioParamConfigValue_len* sizeof(rowreq_ctx->data.audioParamConfigValue[0]));
        if(NULL == (* audioParamConfigValue_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.audioParamConfigValue)\n");
            return MFD_ERROR;
        }
    }
    (* audioParamConfigValue_val_ptr_len_ptr ) = rowreq_ctx->data.audioParamConfigValue_len* sizeof(rowreq_ctx->data.audioParamConfigValue[0]);
    memcpy( (* audioParamConfigValue_val_ptr_ptr ), rowreq_ctx->data.audioParamConfigValue, rowreq_ctx->data.audioParamConfigValue_len* sizeof(rowreq_ctx->data.audioParamConfigValue[0]) );

    return MFD_SUCCESS;
} /* audioParamConfigValue_get */



/** @} */
