/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-access.m2c
 */
#ifndef AUDIOCONFIGTABLE_DATA_ACCESS_H
#define AUDIOCONFIGTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table audioConfigTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * MOSIFY-AUDIO-MIB::audioConfigTable is subid 1 of audioConfigInfo.
 * Its status is Current.
 * OID: .1.3.6.1.3.79.1.1.1, length: 9
*/


    int audioConfigTable_init_data(audioConfigTable_registration * audioConfigTable_reg);


    /*
     * TODO:180:o: Review audioConfigTable cache timeout.
     * The number of seconds before the cache times out
     */
#define AUDIOCONFIGTABLE_CACHE_TIMEOUT   60

void audioConfigTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void audioConfigTable_container_shutdown(netsnmp_container *container_ptr);

int audioConfigTable_container_load(netsnmp_container *container);
void audioConfigTable_container_free(netsnmp_container *container);

int audioConfigTable_cache_load(netsnmp_container *container);
void audioConfigTable_cache_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int audioConfigTable_row_prep( audioConfigTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* AUDIOCONFIGTABLE_DATA_ACCESS_H */
