/*
 * Note: this file originally auto-generated by mib2c
 * using generic-table-oids.m2c
 */
#ifndef AUDIOCONFIGTABLE_OIDS_H
#define AUDIOCONFIGTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table audioConfigTable */
#define AUDIOCONFIGTABLE_OID              1,3,6,1,3,79,1,1,1


#define COLUMN_AUDIOPARAMCONFIGNAME         1
    
#define COLUMN_AUDIOPARAMCONFIGVALUE         2
    

#define AUDIOCONFIGTABLE_MIN_COL   COLUMN_AUDIOPARAMCONFIGNAME
#define AUDIOCONFIGTABLE_MAX_COL   COLUMN_AUDIOPARAMCONFIGVALUE
    


#ifdef __cplusplus
}
#endif

#endif /* AUDIOCONFIGTABLE_OIDS_H */
