/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 *
 * @file audioConfigTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef AUDIOCONFIGTABLE_DATA_GET_H
#define AUDIOCONFIGTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table audioConfigTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * MOSIFY-AUDIO-MIB::audioConfigTable is subid 1 of audioConfigInfo.
 * Its status is Current.
 * OID: .1.3.6.1.3.79.1.1.1, length: 9
*/
    /*
     * indexes
     */

    int audioParamConfigValue_get( audioConfigTable_rowreq_ctx *rowreq_ctx, char **audioParamConfigValue_val_ptr_ptr, size_t *audioParamConfigValue_val_ptr_len_ptr );


int audioConfigTable_indexes_set_tbl_idx(audioConfigTable_mib_index *tbl_idx, char *audioParamConfigName_val_ptr,  size_t audioParamConfigName_val_ptr_len);
int audioConfigTable_indexes_set(audioConfigTable_rowreq_ctx *rowreq_ctx, char *audioParamConfigName_val_ptr,  size_t audioParamConfigName_val_ptr_len);




#ifdef __cplusplus
}
#endif

#endif /* AUDIOCONFIGTABLE_DATA_GET_H */
/** @} */
